import os
import json
import logging
from typing import List, TypedDict, Optional
from dotenv import load_dotenv

from pydantic import BaseModel, Field
from langgraph.graph import StateGraph, END

from langchain_ollama import ChatOllama

# pretty print
from rich.console import Console
from rich.markdown import Markdown
from rich.syntax import Syntax
from rich.logging import RichHandler

# Setup logging
file_handler = logging.FileHandler("app.log", encoding="utf-8")
file_handler.setFormatter(logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s"))

logging.basicConfig(
    level=logging.INFO,
    format="%(message)s",
    datefmt="[%X]",
    handlers=[
        RichHandler(rich_tracebacks=True),
        file_handler
    ]
)
logger = logging.getLogger("reflection")

load_dotenv()

os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_PROJECT"] = "Agentic Architecture - Reflection (Ollama)"

LANGCHAIN_API_KEY = os.environ.get("LANGCHAIN_API_KEY")

if LANGCHAIN_API_KEY is None:
    logger.warning("LANGCHAIN_API_KEY is not set. LangSmith tracing will be disabled.")
else:
    logger.info(f"LANGCHAIN_API_KEY loaded.")

class DraftCode(BaseModel):
    """Schema for the initial code draft generated by the agent."""
    code: str = Field(description="The Python code generated to solve the user request.")
    explanation: str = Field(description="The explanation of the code.")
    
class Critique(BaseModel):
    """Schema for the self-critique of the generated code."""
    has_errors: bool = Field(description="Does the code have any potential bugs or logical errors?")
    is_efficient: bool = Field(description="Is the code written in an efficient and optimal way?")
    suggested_improvements: str = Field(description="Specific, actionable suggestions for improving the code.")
    critique_summary: str = Field(description="A summary of the critique.")

class RefinedCode(BaseModel):
    """Schema for the refined code after self-critique."""
    refined_code: str = Field(description="The refined Python code.")
    refinement_summary: str = Field(description="A summary of the changes made based on the critique.")
    
llm = ChatOllama(model="llama3.1:8b", temperature=0.2)

console = Console()

logger.info("LLM and Console are initialized.")

def generator_node(state):
    """Generates the initial draft of the code."""
    logger.info("--- 1. Generating Initial Draft ---")
    generator_llm = llm.with_structured_output(DraftCode)
    prompt = f"""You are an expert Python programmer. Write a Python function to solve the following request.
    Provide a simple, clear implementation.    
    Request: {state["user_request"]}
    """

    draft = generator_llm.invoke(prompt)
    return {"draft": draft.model_dump()}

