import os
import sys
import json
import logging
from datetime import datetime
from typing import List, TypedDict, Optional
from dotenv import load_dotenv

from pydantic import BaseModel, Field
from langgraph.graph import StateGraph, END

from langchain_ollama import ChatOllama

# pretty print
from rich.console import Console
from rich.markdown import Markdown
from rich.syntax import Syntax
from rich.logging import RichHandler

# Setup logging — tạo file log mới mỗi lần chạy với timestamp
log_filename = datetime.now().strftime("log/app_%Y%m%d_%H%M%S.log")
file_handler = logging.FileHandler(log_filename, encoding="utf-8")
file_handler.setFormatter(logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s"))

logging.basicConfig(
    level=logging.INFO,
    format="%(message)s",
    datefmt="[%X]",
    handlers=[
        RichHandler(rich_tracebacks=True),
        file_handler
    ]
)
logger = logging.getLogger("reflection")

load_dotenv()

os.environ["LANGCHAIN_PROJECT"] = "Agentic Architecture - Reflection (Ollama)"

LANGCHAIN_API_KEY = os.environ.get("LANGCHAIN_API_KEY")

class DraftCode(BaseModel):
    """Schema for the initial code draft generated by the agent."""
    code: str = Field(description="The Python code generated to solve the user request.")
    explanation: str = Field(description="The explanation of the code.")
    
class Critique(BaseModel):
    """Schema for the self-critique of the generated code."""
    has_errors: bool = Field(description="Does the code have any potential bugs or logical errors?")
    is_efficient: bool = Field(description="Is the code written in an efficient and optimal way?")
    suggested_improvements: List[str] = Field(description="Specific, actionable suggestions for improving the code.")
    critique_summary: str = Field(description="A summary of the critique.")

class RefinedCode(BaseModel):
    """Schema for the refined code after self-critique."""
    refined_code: str = Field(description="The refined Python code.")
    refinement_summary: str = Field(description="A summary of the changes made based on the critique.")
    
llm = ChatOllama(model="llama3.1:8b", temperature=0.2)

console = Console()

logger.info("LLM and Console are initialized.")

def generator_node(state):
    """Generates the initial draft of the code."""
    logger.info("--- 1. Generating Initial Draft ---")
    # console.print("--- 1. Generating Initial Draft ---")
    generator_llm = llm.with_structured_output(DraftCode)
    prompt = f"""You are an expert Python programmer. Write a Python function to solve the following request.
    Provide a simple, clear implementation.    
    Request: {state["user_request"]}
    """

    draft = generator_llm.invoke(prompt)

    logger.debug(draft.model_dump())

    return {"draft": draft.model_dump()}

def critic_node(state):
    """Critiques the generated code for errors and inefficiencies."""
    logger.info("--- 2. Critiquing Draft ---")
    # console.print("--- 2. Critiquing Draft ---")
    critic_llm = llm.with_structured_output(Critique)
    
    code_to_critique = state['draft']['code']
    
    prompt = f"""You are an expert code reviewer and senior Python developer. Your task is to perform a thorough critique of the following code.
    
    Analyze the code for:
    1. **Bugs and Errors:** Are there any potential runtime errors, logical flaws, or edge cases that are not handled?
    2. **Efficiency and Best Practices:** Is this the most efficient way to solve the problem? Does it follow standard Python conventions (PEP 8)?
    
    Provide a structured critique with specific, actionable suggestions.
    Code to Review:
    ```python
    {code_to_critique}
    ```
    """

    critique = critic_llm.invoke(prompt)

    logger.debug(critique.model_dump())

    return {"critique": critique.model_dump()} # Corrected: use .model_dump()

def refiner_node(state):
    """Refines the code based on the critique."""
    logger.info("--- 3. Refining Code ---")
    # console.print("--- 3. Refining Code ---")
    
    refiner_llm = llm.with_structured_output(RefinedCode)

    draft_code = state['draft']['code']
    critique_suggestion = json.dumps(state['critique'], indent=2)

    prompt = f"""You are an expert Python programmer tasked with refining a piece of code based on a critique.
    
    Your goal is to rewrite the original code, implementing all the suggested improvements from the critique.

    **Original Code:**
    ```python
    {draft_code}    
    ```

    **Critique and Suggestions:**
    {critique_suggestion}

    Please provide the final, refined code and a summary of the changes you made.
    """

    refined_code = refiner_llm.invoke(prompt)

    logger.debug(refined_code.model_dump())

    return {"refined_code": refined_code.model_dump()} 

class ReflectionState(TypedDict):
    """Represents the state of our reflection graph."""
    user_request: str
    draft: Optional[dict]
    critique: Optional[dict]
    refined_code: Optional[dict]

graph_builder = StateGraph(ReflectionState)

# Add nodes to the graph
graph_builder.add_node("generator_node", generator_node)
graph_builder.add_node("critic_node", critic_node)
graph_builder.add_node("refiner_node", refiner_node)

# Define the workflow edges
graph_builder.set_entry_point("generator_node")
graph_builder.add_edge("generator_node", "critic_node")
graph_builder.add_edge("critic_node", "refiner_node")
graph_builder.add_edge("refiner_node", END)

# Compile the graph
reflection_app = graph_builder.compile()

logger.info("Reflection app is compiled.")

# Visualize the graph
try:
    from IPython.display import Image, display
    png_image = reflection_app.get_graph().draw_png()
    display(Image(png_image))
except ImportError as e:
    logger.warning(f"Graph visualization failed: {e}. Please ensure pygraphviz is installed.")


user_request = "Write a Python function to find the nth Fibonacci number."
initial_input = {"user_request": user_request}

logger.info(f"Kicking off Reflection workflow for request: '{user_request}'")
console.print(f"[bold cyan]:rocket: Kicking off Reflection workflow for request:[/bold cyan] '{user_request}'\n")

# Corrected: This loop correctly captures the final, fully-populated state
final_state = None
for state_update in reflection_app.stream(initial_input, stream_mode="values"):
    final_state = state_update

logger.info("Reflection workflow complete!")
console.print("\n[bold green]:white_check_mark: Reflection workflow complete![/bold green]")

# Check if final_state is available and has the expected keys
if final_state \
    and 'draft' in final_state \
    and 'critique' in final_state \
    and 'refined_code' in final_state:

    md = ""
    md += "--- ### Initial Draft ---\n\n"
    md += f"**Explanation:** {final_state['draft']['explanation']}\n\n"
    md += "```python\n"
    md += final_state['draft']['code']
    md += "\n```\n\n"

    md += "\n--- ### Critique ---\n\n"
    md += f"**Summary:** {final_state['critique']['critique_summary']}\n\n"
    md += f"**Improvements Suggested:** {final_state['critique']['suggested_improvements']}\n\n"
    for improvement in final_state['critique']['suggested_improvements']:
        md += f"- {improvement}"
    
    md += "--- ### Refined Code ---\n\n"
    md += f"**Refinement Summary:** {final_state['refined_code']['refinement_summary']}\n\n"    
    md += final_state['refined_code']['refined_code']
    md += "\n\n"

    logger.info(md)
    console.print(Markdown(md))

else:
    logger.error("The `final_state` is not available or is incomplete. Please check the execution of the previous cells.")
    
class CodeEvaluation(BaseModel):
    """Schema for the code evaluation."""
    correctness_score: int = Field(description="Score from 1-10 on whether the code is logically correct.")
    efficiency_score: int = Field(description="Score from 1-10 on the code's algorithmic efficiency.")
    style_score: int = Field(description="Score from 1-10 on code style and readability (PEP 8). ")
    justification: str = Field(description="A brief justification for the scores.")

judge_llm = llm.with_structured_output(CodeEvaluation)

def evaluate_code(code_to_evaluate: str):
    prompt = f"""You are an expert judge of Python code. Evaluate the following function on a scale of 1-10 for correctness, efficiency, and style. Provide a brief justification.

    Code:
    ```python
    {code_to_evaluate}
    ```
    """
    return judge_llm.invoke(prompt)

if final_state and 'draft' in final_state and 'refined_code' in final_state:
    console.print("--- Evaluating Initial Draft ---")
    initial_draft_evaluation = evaluate_code(final_state['draft']['code'])
    console.print(initial_draft_evaluation.model_dump()) # Corrected: use .model_dump()

    console.print("\n--- Evaluating Refined Code ---")
    refined_code_evaluation = evaluate_code(final_state['refined_code']['refined_code'])
    console.print(refined_code_evaluation.model_dump()) # Corrected: use .model_dump()
else:
    console.print("[bold red]Error: Cannot perform evaluation because the `final_state` is incomplete.[/bold red]")

